### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by adamjonas** [adamjonas/chat-btc-next#28]
![image](https://github.com/adamjonas/chat-btc-next/assets/755825/5028e2cb-40ac-4a5b-8da7-2e50163cb0b1)

**Comment by Emmanuel-Develops** [comment]
I can't recreate this, not on firefox web or mobile (macOs | iOS). I did change some css and layout structure in #33 so maybe that fixed it.

**Comment by adamjonas** [comment]
User says it was his setup, not our site
